# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2a84f205ecafd84422ef902c9820b06132967d7de48b27d97d17d82d978694f0f571f293b0b4ad0d144992e423342b76fb6db384eafc7b9998307cf8b30194f

test:
  secret_key_base: 84bce1935f3d3068bcefac8f5c3ca907004daf62327df35407364e8efc690af42268157b4c36c8ffb19d7cd26a5c1dd23e8b3c902c244d4df99db2de1519a9dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
